language: c
sudo: required
dist: xenial
addons:
  apt:
    packages:
      - gfortran
      - mpich
      - libmpich-dev
    config:
      retries: true

matrix:
  include:
    - env: TEST=crystal_test
    - env: TEST=findpts_el_2_test
    - env: TEST=findpts_el_2_test2
    - env: TEST=findpts_el_3_test
    - env: TEST=findpts_el_3_test2
    - env: TEST=findpts_el_2_test2
    - env: TEST=findpts_local_test
    - env: TEST=findpts_test
    - env: TEST=gs_test
    - env: TEST=gs_test_gop_nonblocking
    - env: TEST=gs_test_gop_blocking
    - env: TEST=gs_unique_test
    - env: TEST=lob_bnd_test
    - env: TEST=obbox_test
    - env: TEST=poly_test
    - env: TEST=sarray_sort_test
    - env: TEST=sarray_transfer_test
    - env: TEST=sort_test
    - env: TEST=sort_test2

install:
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_C_COMPILER=mpicc -DCMAKE_Fortran_COMPILER=mpif90 -DNBC=on ..
  - make ${TEST}

script:
  - mpirun -np 2 ./${TEST}
